[package]
name = "game"
version = "0.1.0"
authors = ["Cedric Hutchings <cedhut02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# windowing, rendering, input, etc.
macroquad = "0.2.9"

# ecs
hecs = { git = "https://github.com/Ralith/hecs.git" }
l8r = { git = "https://github.com/cedric-h/l8r.git" }

# maffs
ncollide2d = "0.24.0"
na = { package = "nalgebra", version = "0.22.0"}

# serialization
fxhash = "0.2.1"

# util
rand = "0.7.2"
glam = {version = "0.8", features = ["scalar-math"] }
miniquad = { version = "=0.3.0-alpha.11" }
