[package]
name = "game"
version = "0.1.0"
authors = ["Cedric Hutchings <cedhut02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
hitbox-outlines = []

[dependencies]
quicksilver = "0.3.20"
hecs = "0.2.5"
ncollide2d = "0.20.0"
nalgebra = "0.18.0"
