keyframes = [
	{ time = 0.0, pos = [0, 0], rot = 25, bottom_padding = 0 },
	{ time = 0.2, pos = [0.4, -0.5], rot = 45, bottom_padding = -1},
	{ time = 0.5, rot = 190, bottom_padding = -10 },
	{ time = 0.8, rot = 360, bottom_padding = 0 },
]

tilemap = """\
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrDiGrGrGrGrGrGrGrGrDiGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrDiGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiGrGrDiDiGrDiGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDiDiDiDiDiDiDiDiDiDiGrDiGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiDiDiDiDiDiDiDiDiDiGrGrGr
GrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrDiGrDiDiDiGrDiGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGr
GrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
"""

[tiles.Gr]
name = "Grass"
image = "grass"

[tiles.Di]
name = "Dirt"
image = "dirt"

[tiles.Fr]
name = "Field Ready"
image = "field-ready"
farmable = true

[tiles.Bd]
name = "Bad"
image = "unknown"
collidable = true

[player]
speed = 0.1
image = "creep"
size = [0.7, 0.3]
pos = [15.0, 8.5]

