
tilemap = """\
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrDiGrGrGrGrGrGrGrGrDiGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrDiGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiGrGrDiDiGrDiGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDiDiDiDiDiDiDiDiDiDiGrDiGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiDiDiDiDiDiDiDiDiDiGrGrGr
GrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrDiGrDiDiDiGrDiGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGr
GrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
"""

[weapons.spear]
# appearance
image = "spear"
readying_time = 60
equip_time = 60
equip_keyframes = [
	{ time = 0.0, pos = [-0.2, -0.4], rot = -25, bottom_padding = -0.5 },
	{ time = 0.2, pos = [0.5, -0.8], rot = -45, bottom_padding = -0.4 },
	{ time = 0.4, pos = [0.6, -0.9], rot = -200, bottom_padding = -0.6 },
	{ time = 0.6, pos = [0.0, -0.7], rot = -350, bottom_padding = -0.3 },
	{ time = 0.7, rot = 25, bottom_padding = 0.2}
]
# default (readied) positioning
offset = [0.115, -0.385]
bottom_padding = 0.325
# projectile
force_magnitude = 2.125
force_decay = 0.75
minimum_speed_to_damage = 0.05
speed_damage_coefficient = 1.0
minimum_damage = 1
damage = 1
# side effects
player_knock_back_force = 0.5
player_knock_back_decay = 0.75

[weapons.flower_power]
# appearance
image = "flower_power"
readying_time = 60
equip_time = 60
equip_keyframes = [
	{ time = 0.0, pos = [-0.2, -0.4], rot = -25, bottom_padding = -0.5 },
	{ time = 0.2, pos = [0.5, -0.8], rot = -45, bottom_padding = -0.4 },
	{ time = 0.4, pos = [0.6, -0.9], rot = -200, bottom_padding = -0.6 },
	{ time = 0.6, pos = [0.0, -0.7], rot = -350, bottom_padding = -0.3 },
	{ time = 0.7, rot = 25, bottom_padding = 0.2}
]
# default (readied) positioning
offset = [0.115, -0.385]
bottom_padding = 0.325
# projectile
force_magnitude = 0.325
force_decay = 0.98
minimum_speed_to_damage = 0.1
speed_damage_coefficient = 3.0
minimum_damage = 2
damage = 1
# side effects
player_knock_back_force = 0.5
player_knock_back_decay = 0.75

[player]
speed = 0.1
image = "creep"
size = [0.7, 0.3]
pos = [15.0, 8.5]
inventory = [
	{ name = "spear", count = 99, flags = ["equipped"] },
	{ name = "flower_power" },
]

[tiles.Gr]
name = "Grass"
image = "grass"

[tiles.Di]
name = "Dirt"
image = "dirt"

[tiles.Fr]
name = "Field Ready"
image = "field-ready"
farmable = true

[tiles.Bd]
name = "Bad"
image = "unknown"
collidable = true

[sprite_sheets.creep]
frame_size = [24, 24]
rows = 2
cols = 1
frame_millis = [
	250,
	250
]

