# speed doesn't work yet
player = { speed = 4, image = "ferris", size = [58, 8], pos = [300, 300] }

keyframes = [
	{ time = 0.0, pos = [0, 0], rot = 25, bottom_padding = 0.0 },
	{ time = 0.2, pos = [40, -50], rot = 45, bottom_padding = -60.0 },
	{ time = 0.5, rot = 190, bottom_padding = -10 },
	{ time = 0.8, rot = 360, bottom_padding = 0 },
]

tilemap = """\
gr,gr,gr,gr,gr
di,di,di,di,di
gr,di,gr,di,gr
di,gr,di,gr,di
gr,gr,di,di,gr
gr,gr,di,di,gr
gr,gr,gr,gr,gr
fr,fr,fr,fr,bd
"""

[tiles.gr]
name = "Grass"
image = "grass"

[tiles.di]
name = "Dirt"
image = "dirt"

[tiles.fr]
name = "Field Ready"
image = "field-ready"
farmable = true

[tiles.bd]
name = "Bad"
image = "unknown"
collidable = true
