
tilemap = """\
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrDi
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrDiGrGrGrGrGrGrGrGrDiGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrDiGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiGrGrDiDiGrDiGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiDiDiDiDiDiDiDiDiDiDiGrDiGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrDiDiDiDiDiDiDiDiDiDiDiGrGrGr
GrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrFrFrFrFrFrFrFrFrGrGrGrGrGr
GrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrDiGrDiDiDiGrDiGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrDiGrGrGrGrGr
GrGrGrGrGrGrGrGrGrDiGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
GrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGrGr
"""

[animations]
spear_equip = [
	{ time = 0.0, pos = [-0.2, -0.4], rot = -25, bottom_padding = -0.5 },
	{ time = 0.2, pos = [0.5, -0.8], rot = -45, bottom_padding = -0.4 },
	{ time = 0.4, pos = [0.6, -0.9], rot = -200, bottom_padding = -0.6 },
	{ time = 0.6, pos = [0.0, -0.7], rot = -350, bottom_padding = -0.3 },
	{ time = 0.7, rot = 25, bottom_padding = 0.2}
]

[items.spear_leaflet]
image = "spear_leaflet"
growth = { after = "spear_sapling", duration = 60 }

[items.spear_sapling]
image = "spear_sapling"
growth = { after = "spear_sprout", duration = 60 }

[items.spear_sprout]
image = "spear_sprout"
growth = { after = "spear_strong", duration = 60 }

[items.spear_strong]
image = "spear_strong"
growth = { after = "spear", duration = 60 }

[items.spear]
image = "spear"
[items.spear.weapon]
	# default (readied) positioning
	bottom_padding = 0.325
	offset = [0.115, -0.385]
	# animations
	readying_time = 60
	equip_time = 60
	animations = "spear_equip"
	# projectile
	force_magnitude = 2.125
	force_decay = 0.75
	# side effects
	player_knock_back_force = 0.5
	player_knock_back_decay = 0.75
[items.spear.hurtful]
	minimum_speed = 0.05
	raw_damage = 1
	minimum_damage = 1
	kind = { Ram = { speed_damage_coefficient = 1.0 } }

[items.flower_power]
image = "flower_power"
[items.flower_power.weapon]
	# default (readied) positioning
	bottom_padding = 0.325
	offset = [0.115, -0.385]
	# animations
	readying_time = 60
	equip_time = 60
	animations = "spear_equip"
	# projectile
	force_magnitude = 0.325
	force_decay = 0.98
	# side effects
	player_knock_back_force = 0.5
	player_knock_back_decay = 0.75
[items.flower_power.hurtful]
	minimum_speed = 0.1
	raw_damage = 1
	minimum_damage = 2
	kind = { Ram = { speed_damage_coefficient = 3.0 } }

[particles.arterial_spray]
life_cycle = { Duration = { frames = 50 } }
particle_count = "2..=3"
# particle config
force_magnitude = "0.4..=0.6"
force_decay = "0.7..=0.8"
particle_duration = "100"
particle_duration_fade = "25"
color = ["0.65..0.85", "0.0..0.1", "0.0..0.1", "1.0"]
size = ["0.1..0.2", "0.0"]
square = true

[particles.planting_cursor]
life_cycle = { Immortal = {} }
particle_count = "4..=6"
direction_bounds = [15, -15]
# particle config
force_magnitude = "0.1..=0.15"
force_decay = "0.9..=0.98"
particle_duration = "50"
particle_duration_fade = "50"
color = ["0.0..0.75", "0.7..0.9", "0.2..0.35", "1.0"]
size = ["0.1..0.2", "0.0"]
square = true

[particles.blood_splash]
# emitter config
life_cycle = { Duration = { frames = 3 } }
particle_count = "1"
direction_bounds = [-15, 15]
# particle config
force_magnitude = "0.6..=0.9"
force_decay = "0.85..=0.9"
particle_duration = "100"
particle_duration_fade = "25"
color = ["0.65..0.85", "0.0..0.1", "0.0..0.1", "1.0"]
size = ["0.1..0.2", "0.0"]
square = true

[particles.bread_splatter]
life_cycle = { Duration = { frames = 1 } }
particle_count = "4..=6"
direction_bounds = [15, -15]
# particle config
force_magnitude = "0.6..=0.8"
force_decay = "0.8..=0.85"
particle_duration = "250"
particle_duration_fade = "50"
color = ["0.96", "0.87", "0.70", "1.0"]
size = ["0.3..0.6", "0.0"]
square = true

[player]
speed = 0.1
image = "creep"
size = [0.7, 0.3]
pos = [15.0, 8.5]
inventory = [
	{ name = "spear", count = 99, flags = ["equipped"] },
	{ name = "flower_power"},
]

[tiles.Gr]
name = "Grass"
image = "grass"

[tiles.Di]
name = "Dirt"
image = "dirt"

[tiles.Fr]
name = "Field Ready"
image = "field-ready"
farmable = true

[tiles.Bd]
name = "Bad"
image = "unknown"
collidable = true

[sprite_sheets.creep]
frame_size = [24, 24]
rows = 2
cols = 1
frame_millis = [
	250,
	250
]

